#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

PADDINGS=4

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
ICON_FONT="sketchybar-app-font" # Custom font for icons




# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=39
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=0
  margin=0
  blur_radius=20
  notch_width=200
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  icon.font="$ICON_FONT:Regular:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=10
  label.padding_right=10
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/aerospace.sh"
# source "$ITEM_DIR/spaces.sh"


# Notch Left
source "$ITEM_DIR/front_app.sh"
# source "$ITEM_DIR/spotify.sh"
# Notch Right
source "$ITEM_DIR/media.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
sketchybar --trigger space_change


echo "sketchybar configuation loaded.."